name: Security CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: SAST - SonarQube
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          output: sonarqube.json

      - name: Upload Sonarqube results as artifact
        uses: actions/upload-artifact@v6
        with:
          name: sonarqube-results
          path: sonarqube.json

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: SCA - Snyk
        uses: snyk/actions/python@9adf32b1121593767fc3c057af55b55db032dc04
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          output: snyk.json

      - name: Upload Snyk results as artifact
        uses: actions/upload-artifact@v6
        with:
          name: snyk-results
          path: snyk.json

  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker image
        run: docker build -t password-manager:${{ github.sha }} .

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          output: trivyfs.json

      - name: Upload Trivy file scan results as artifact
        uses: actions/upload-artifact@v6
        with:
          name: trivy-file-scan-results
          path: trivyfs.json
      
      - name: Trivy container scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: image
          image-ref: 'password-manager:${{ github.sha }}'
          format: json
          exit-code: 0
          output: trivyimage.json

      - name: Upload Trivy image scan results as artifact
        uses: actions/upload-artifact@v6
        with:
          name: trivy-image-scan-results
          path: trivyimage.json